name: singbox_uninstall

on:
  workflow_dispatch:  # 支持手动执行  

jobs:
  singbox_uninstall:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server: [1, 2, 3, 4]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set common secrets
        run: |
          echo "SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }}" >> $GITHUB_ENV
          echo "SERVER_PASSWORD=${{ secrets.SERVER_PASSWORD }}" >> $GITHUB_ENV

      - name: Set server-specific variables
        run: |
          case "${{ matrix.server }}" in
            1)
              echo "SERVER_USERNAME=coffeebabysoster" >> $GITHUB_ENV
              ;;
            2)
              echo "SERVER_USERNAME=coffeebabyheart" >> $GITHUB_ENV
              ;;
            3)
              echo "SERVER_USERNAME=coffeebabyworker" >> $GITHUB_ENV
              ;;
            4)
              echo "SERVER_USERNAME=coffeebabybaby" >> $GITHUB_ENV
              ;;
          esac
            
      - name: Install sshpass
        run: sudo apt-get install -y sshpass || echo "sshpass already installed"

      - name: SSH into server and run script
        run: |
          sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} -o ConnectTimeout=10 2>/tmp/ssh_error.log || {
            echo -e "\033[31mSSH connection failed! Please check your SSH credentials or server status.\033[0m"
            echo -e "\033[31mError details:\033[0m"
            cat /tmp/ssh_error.log
            exit 1
           }
           
          sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
            set -e 
            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/singbox_uninstall.sh -o singbox_uninstall.sh || { echo 'Script download failed'; exit 1; }
            bash singbox_uninstall.sh || { echo 'Script execution failed'; exit 1; }
          EOF
